name: 'Changed Files Exporter'
description: 'Exports the files created, modified or deleted by a PR'
author: 'Duarte Nunes <duarte.m.nunes@gmail.com'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  pattern:
    description: 'A regular expression to filter the outputs by.'
    required: false
    default: '.*'
  pr-number:
    description: 'The pull request number (if absent, the pull request is inferred from the given context).'
    required: false
outputs:
  files_created:
    description: 'The names of the newly created files'
  files_updated:
    description: 'The names of the updated files'
  files_deleted:
    description: 'The names of the deleted files'
runs:
  using: 'node12'
  main: 'dist/main.js'
branding:
  icon: 'wind'
  color: 'green'
